COMPILER=mpicc
MAIN_SOURCE_FILE=app/main.c
OUTPUT_FOLDER=dist
DISTRIBUTION_NAME=app

build: $(SRC_FILES)
	$(COMPILER) -o $(OUTPUT_FOLDER)/$(DISTRIBUTION_NAME) $(MAIN_SOURCE_FILE)
	chmod 755 $(OUTPUT_FOLDER)/$(DISTRIBUTION_NAME)

